"""Max length to password

Revision ID: 03a6a4bd82f4
Revises: ebfab1ba3536
Create Date: 2023-07-09 10:46:07.855126
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '03a6a4bd82f4'
down_revision = 'ebfab1ba3536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'password',
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'password',
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
